programs_list = {
    "ascii_pic":        "programs/ascii_pic.py",
    "blink_sun":        "programs/blink_sun.py",
    "cross":            "programs/cross.py",
    "demo":             "programs/demo.py",
    "figlet":           "programs/figlet.py",
    "game_of_life":     "programs/game_of_life.py",
    "matrix":           "programs/matrix.py",
    "psychedelia":      "programs/psychedelia.py",
    "rain":             "programs/rain.py",
    "rainbow":          "programs/rainbow.py",
    "random_blinky":    "programs/random_blinky.py",
    "random_sparkles":  "programs/random_sparkles.py",
    "simple":           "programs/simple.py",
    "snow":             "programs/snow.py",
    "trig":             "programs/trig.py",
}